def start_screen
##Drawing goes here

Curses.setpos(1,20)
Curses.addstr("                                  _,-----------._                  ")
Curses.setpos(2,20)
Curses.addstr(" ______________               _,-'_,-----------._`-._             ")
Curses.setpos(3,20)
Curses.addstr("|              |            ,'_,-'  ___________  `-._`.           ")
Curses.setpos(4,20)
Curses.addstr("| THE DIMMEST  |          ,','  _,-'___________`-._  `.`.         ")
Curses.setpos(5,20)
Curses.addstr("|   DUNGEON    |        ,','  ,'_,-'     .     `-._`.  `.`.       ")
Curses.setpos(6,20)
Curses.addstr("|______________|       /,'  ,','        >|<        `.`.  `.\\      ")
Curses.setpos(7,20)
Curses.addstr("                      //  ,','      ><  ,^.  ><      `.`.  \\\\     ")
Curses.setpos(8,20)
Curses.addstr("                     //  /,'      ><   / | \\   ><      `.\\  \\\\    ")
Curses.setpos(9,20)
Curses.addstr("                    //  //      ><    \\/\\^/\\/    ><      \\\\  \\\\   ")
Curses.setpos(10,20)
Curses.addstr("                   ;;  ;;              `---'              ::  ::  ")
Curses.setpos(11,20)
Curses.addstr("                   ||  ||             (_____)             ||  ||  ")
Curses.setpos(12,20)
Curses.addstr("                  _||__||_            ,'----.            _||__||_ ")
Curses.setpos(13,20)
Curses.addstr("                 (o.____.o)____        `---'        ____(o.____.o)")
Curses.setpos(14,20)
Curses.addstr("                   |    | /,--.)                   (,--.\ |    |  ")
Curses.setpos(15,20)
Curses.addstr("                   |    |((  -`___               ___`   ))|    |  ")
Curses.setpos(16,20)
Curses.addstr("                   |    | \\\\,'',  `.           .'  .``.// |    |  ")
Curses.setpos(17,20)
Curses.addstr("                   |    |  // (___,'.         .'.___) \\\\  |    |  ")
Curses.setpos(18,20)
Curses.addstr("                 /|    | ;;))  ____) .     . (____  ((\\ |    |\\  ")
Curses.setpos(19,20)
Curses.addstr("                  \\|.__ | ||/ .'.--.\\/       `/,--.`. \;: | __,|; ")
Curses.setpos(20,20)
Curses.addstr("                   |`-,`;.| :/ /,'  `)-'   `-('  `.\\ \\: |.;',-'|  ")
Curses.setpos(21,20)
Curses.addstr("                   |   `..  ' / \__.'         `.__/ \\ `  ,.'   |  ")
Curses.setpos(22,20)
Curses.addstr("                   |    |,\\  /,                     ,\\  /,|    |  ")
Curses.setpos(23,20)
Curses.addstr("                   |    ||: : )          .          ( : :||    |  ")
Curses.setpos(24,20)
Curses.addstr("                  /|    |:; |/  .      ./|\\,      ,  \| :;|    |\\ ")
Curses.setpos(25,20)
Curses.addstr("                  \\|.__ |/  :  ,/-    <--:-->    ,\\.  ;  \\| __,|; ")
Curses.setpos(26,20)
Curses.addstr("                   |`-.``:   `'/-.     '\\|/`     ,-\`;   ;'',-'|  ")
Curses.setpos(27,20)
Curses.addstr("                   |   `..   ,' `'       '       `  `.   ,.'   |  ")
Curses.setpos(28,20)
Curses.addstr("                   |    ||  :                         :  ||    |  ")
Curses.setpos(29,20)
Curses.addstr("                   |    ||  |                         |  ||    |  ")
Curses.setpos(30,20)
Curses.addstr("                   |    ||  |                         |  ||    |  ")
Curses.setpos(31,20)
Curses.addstr("                   |    |'  |            _            |  `|    |  ")
Curses.setpos(32,20)
Curses.addstr(" Created by:       |    |   |          '|))           |   |    |  ")
Curses.setpos(33,20)
Curses.addstr("Nicholas Dunlap    ;____:   `._        `'           _,'   ;____:  ")
Curses.setpos(34,20)
Curses.addstr("    &&            {______}     \\___________________/     {______} ")
Curses.setpos(35,20)
Curses.addstr(" Katana Tran      |______|_______________________________|______| ")
Curses.setpos(37,20)
Curses.addstr("                         WILL RICHES OR DEATH BE YOUR FATE?       ")
Curses.setpos(39,20)
Curses.addstr("                              Press any key to begin...           ")
Curses.getch
end